### ISSUE TITLE
FEATURE REQUEST: create symlinks to `/var/log/socklog/whatever/current` in other locations

### ISSUE THREAD

**Issue by ehudkaldor** [just-containers/socklog-overlay#5]
I don't know how prevalent it is, but some applications (or humans, for that matter) expect logs to be in specific places. it will not do good to state a different location for the logs, as the structure will still be foreign (`/var/log/socklog/whatever/current' instead of `/var/log/whatever.log`).

So, it will be very convenient to have a way to automatically create symlinks (`ln -s`) that point to `current` in the right spot. that way, socklog takes care of syslog and rotation, the symlink is always fresh (as it will keep pointing to `current` even if the file is swapped), and there will be much rejoicing. 

(I create those symlinks manually in `/etc/cont-init.d` manually, for now)

**Comment by jprjr** [comment]
I don't think there's not a lot of value in automatically creating symlinks, since it's pretty easy to do (just place a few calls to `ln -s` in a `/etc/cont-init.d` script, or in your `Dockerfile`, either way).

The main reason for creating `/etc/socklog.rules` is mostly around people not being used to using `execline` and its tools/way of operating, but `ln` is pretty well-understood.
